server:
  port: 8002

spring:
  application:
    name: cloud-payment-service
  datasource:
    username: root
    password: sa007
    url: jdbc:mysql://127.0.0.1:3306/cloud?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#   url: jdbc:mysql://127.0.0.1:3306/cloud?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bp.springcloud.entities

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8002
    prefer-ip-address: true
